### ISSUE TITLE
KCT additional launchpads are not handled by the Construction system

### ISSUE THREAD

**Issue by vardicdestroyer** [severedsolo/Bureaucracy#3]
Plan for future adjustments to deal with KCT building additional launchpads at KSC instantly when using Bureaucracy mod, with KCT build times turned off. 
Addendum: Additional KCT launchpads also can not seem to be upgraded when using Bureaucracy
{hope this is what you meant?}

**Comment by severedsolo** [comment]
Thank you - just because when I'm doing updates I tend to miss stuff in the forum thread, and I'm just concentrating on bug fixes at the moment. If it's on here I'm more likely to remember it :)

**Comment by severedsolo** [comment]
Removed the enhancement label because it's not really an enhancement, it should handle this but can't until I write some code for KCT to make it work
