### ISSUE TITLE
Close Dialog when button toolbar button clicked

### ISSUE THREAD

**Issue by astrolamb-gaming** [severedsolo/Bureaucracy#4]
A small quality of life thing that most mods implement is when the dialog is open and you click the button on the toolbar again, the dialog closes. I think if this was implemented for at least the Budget dialog it would be sufficient for most cases. People like me often click through each of the buttons on the toolbar, hitting them again to close it shortly thereafter, and having to move the mouse all the way to the close button isn't ideal from a ux perspective.

**Comment by severedsolo** [comment]
This is an issue with the UI system that I'm using.

The mods you are talking about use the old (and deprecated) "OnGUI" method to draw the UI. That particular system has a few drawbacks that make it unsuitable for Bureaucracy - mainly the fact it draws the UI on every frame.

Cause Bureaucracy pokes it's fingers into alot of places, and stores alot of data, pulling that data every frame causes massive issues with the Garbage Collector and leads to massive framerate issues. 

PopUpDialog (which is the system I use) only redraws the window when it absolutely has to, and pulls the data once, unless it changes, but the tradeoff for that is the fact it locks the UI.

**Comment by severedsolo** [comment]
and I should eat my hat... because I was overlooking a boolean that turns the lock off.

I'll try and get this into the next release

**Comment by astrolamb-gaming** [comment]
\o/ Thanks!

**Comment by severedsolo** [comment]
Done for 1.4
